--Act 2--

DESC tablename;

select * from tablename;

insert into tablename
values (1,'mahesh','pune',12);

insert into tablename
values (2,'Vijay','mumbai',13);

insert into tablename
values (3,'Kiran','Nashik',14);

insert into tablename
values (4,'Ganesh','pune',15);

insert into tablename
values (1,'rajkumar','Beed',16);


insert all
INTO tablename VALUES(5, 'Pit Alex', 'London', 17)
    INTO tablename VALUES(7, 'McLyon', 'Paris', 18)
    INTO tablename VALUES(8, 'Paul Adam', 'Rome', 19)
    INTO tablename VALUES(9, 'Lauson Hen', 'San Jose', 20)
select 1 from dual;

select * from tablename;
